import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "start",
    alignItems: "start",
    paddingLeft: 20,
  },
  //------------ Bottom Tabs ----------
  qrIcon: {
    backgroundColor: "#c29555",
    padding: 15,
    borderRadius: 50,
    position: "absolute",
    top: -30,
  },
  tabIcon: {
    marginTop: 15,
    flexDirection: "column",
    alignItems: "center",
  },
  activeQr: {
    backgroundColor: "#db7c00",
    padding: 20,
    borderRadius: 50,
    position: "absolute",
    top: -30,
  },
  tabLabel: {
    fontFamily: "Poppins_Medium",
    marginTop: 0,
    paddingBottom: 2,
    color: "#db7c00",
    borderBottomWidth: 3,
    borderBottomColor: "#c29555",
    marginBottom: -8,
    fontSize: 12,
  },
  label: {
    fontFamily: "Poppins_Medium",
    marginTop: 0,
    paddingBottom: 2,
    color: "#c29555",
    marginBottom: -8,
    fontSize: 12,
  },

  //------------ Dashboard ----------
  dashboardTopContent: {
    flexDirection: "row",
    alignItems: "start",
    justifyContent: "space-between",
    marginTop: 50,
    marginRight: 20,
  },
  topArrowContainer: {
    //backgroundColor: "#2d2e2e",
    width: 40,
    height: 40,
    borderRadius: 50,
    shadowColor: "#000",
    shadowOpacity: 1,
    shadowRadius: 30,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    elevation: 10,
    alignItems: "center",
    justifyContent: "center",
  },

  topArrow: {},
  rightTopContent: {
    flexDirection: "row",
    alignItems: "start",
  },

  notifyImg: {
    width: 26,
    height: 26,
    marginTop: 8,
  },
  profileImg: {
    width: 50,
    height: 56,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#2d2e2e",
  },
  profileContainer: {
    width: 48,
    height: 66,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 30,
    shadowOpacity: 1,
    elevation: 10,
    backgroundColor: "transparent",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "end",
    marginRight: 20,
  },
  recentText: {
    color: "#fff",
    fontFamily: "Poppins_Regular",
    opacity: 0.5,
    marginTop: 30,
    fontSize: 16,
  },
  RecentBillarContainer: {
    marginTop: 20,
    //paddingHorizontal: 8,
    maxHeight: 140,
  },
  mainRecentConatiner: {
    width: 130,
    height: 117,
    borderRadius: 20,
    marginRight: 15,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 20,
    shadowOpacity: 0.8,
    elevation: 10,
  },
  recentCards: {
    width: 130,
    height: 115,
    flexDirection: "column",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingVertical: 20,
    justifyContent: "space-between",
    borderRadius: 20,
  },
  imageShadow: {
    width: 50,
    height: 50,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 30,
    shadowOpacity: 1,
    elevation: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  recentCardImg: {
    width: 30,
    height: 20,
    objectFit: "contain",
  },
  recentCardTitle: {
    color: "#fff",
    fontFamily: "Poppins_Medium",
    opacity: 0.5,
  },
  boldText: {
    color: "#fff",
    fontFamily: "Poppins_Medium",
    fontSize: 16,
    opacity: 0.6,
    marginTop: 30,
  },
  searchMainConatiner: {
    height: 54,
    marginVertical: 10,
    borderRadius: 14,
    borderWidth: 0.7,
    borderColor: "#383838",
    shadowColor: "#4e4d4f",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowRadius: 30,
    shadowOpacity: 1,
    elevation: 10,
    borderBottomWidth: 0,
    marginRight: 20,
  },
  searchContainer: {
    paddingHorizontal: 20,
    height: 50,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 14,
  },
  inputText: {
    color: "#4b4b4d",
    fontFamily: "Poppins_Regular",
  },
  searchIcon: {
    marginLeft: -20,
  },
  billarMainContainer: {
    marginTop: 30,
    maxHeight: 190,
  },
  billarConatiner: {
    width: 132,
    height: 177,
    borderRadius: 20,
    marginRight: 25,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 30,
    shadowOpacity: 1,
    elevation: 10,
  },
  billarCards: {
    width: 140,
    height: 175,
    flexDirection: "column",
    alignItems: "flex-start",
    paddingHorizontal: 15,
    paddingVertical: 20,
    justifyContent: "space-between",
    borderRadius: 20,
  },
  billarTitle: {
    color: "#c29555",
    fontFamily: "Poppins_Medium",
    opacity: 0.8,
    fontSize: 15,
  },
  codeText: {
    color: "#6d6f70",
    fontFamily: "Poppins_Medium",
    opacity: 0.9,
    fontSize: 10,
    marginBottom: -10,
    marginTop: 15,
  },
  typeText: {
    color: "#6d6f70",
    fontFamily: "Poppins_Medium",
    opacity: 0.7,
    fontSize: 11,
    marginTop: -10,
  },

  //------------ Wallet Screen ----------
  headText: {
    color: "#fff",
    opacity: 0.5,
    fontFamily: "Lato_Regular",
    fontSize: 26,
    letterSpacing: 0.5,
    textShadowColor: "#000",
    textShadowOffset: {
      width: 2,
      height: 2,
    },
    textShadowRadius: 20,
  },
  walletMainContainer: {
    height: 184,
    marginTop: 30,
    shadowColor: "#fff",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowRadius: 20,
    shadowOpacity: 1,
    elevation: 20,
  },
  walletContainer: {},
  walletCard: {
    height: 180,
    borderRadius: 20,
    opacity: 0.8,
    marginTop: -5,
    marginLeft: 2,
    shadowColor: "#faa15c",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowRadius: 20,
    shadowOpacity: 1,
    elevation: 50,
    paddingHorizontal: 30,
    paddingVertical: 20,
    flexDirection: "column",
    justifyContent: "space-between",
  },
  visaText: {
    fontFamily: "Poppins_BoldItalic",
    fontSize: 24,
    color: "#fff",
  },
  cardTopContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  miniText: {
    color: "#fff",
    opacity: 0.7,
    fontSize: 12,
    fontFamily: "Poppins_Medium",
  },
  dollerText: {
    color: "#fff",
    fontSize: 28,
    fontFamily: "Nunito_Regular",
    letterSpacing: 1.2,
  },
  starText: {
    color: "#fff",
    fontSize: 20,
    fontFamily: "Nunito_Regular",
    letterSpacing: 1.2,
  },
  normalText: {
    color: "#fff",
    fontSize: 18,
    fontFamily: "Poppins_Regular",
    letterSpacing: 1.2,
  },
  historyContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 30,
  },

  historyMainContainer: {
    marginVertical: 15,
    marginBottom: 100,
  },
  historyItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    paddingVertical: 10,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: "#383838",
    borderRadius: 4,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowRadius: 20,
    shadowOpacity: 1,
    elevation: 20,
  },
  rightContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  imageContainer: {
    //backgroundColor: "#2d2e2e",
    width: 60,
    height: 60,
    borderRadius: 50,
    shadowColor: "#000",
    shadowOpacity: 1,
    shadowRadius: 30,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    elevation: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  imageShadow: {
    width: 70,
    height: 70,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowRadius: 30,
    shadowOpacity: 1,
    elevation: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  billerTitle: {
    color: "#fff",
    fontFamily: "Poppins_Medium",
    opacity: 0.5,
    fontSize: 14,
  },
  codeId: {
    color: "#6d6f70",
    fontFamily: "Poppins_Medium",
    opacity: 0.9,
    fontSize: 12,
  },
  typeText: {
    color: "#6d6f70",
    fontFamily: "Poppins_Medium",
    opacity: 0.9,
    fontSize: 11,
  },
  paymentText: {
    color: "#c29555",
    opacity: 1,
    marginVertical: 5,
  },
});

export default styles;
